name: 'PMD Automatic reviewer'
author: Matias Kruk
description: 'This action allows to use PMD Source Code Analyzer from GitHub Actions and publish by Salesforce API REST'
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'award'  
  color: 'red'
